# Generated by Django 5.2 on 2025-05-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_creditpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(blank=True, choices=[('Maganjo', 'Maganjo'), ('Matugga', 'Matugga')], max_length=20, null=True),
        ),
    ]
