# Generated by Django 5.2 on 2025-04-19 11:39

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Maganjo', 'Maganjo'), ('Matugga', 'Matugga')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('produce_type', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_salesagent', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('address', models.TextField(max_length=200)),
                ('phonenumber', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='userprofile_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='userprofile_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('tonnage_kgs', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000)])),
                ('costUgx', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(10000)], verbose_name='Cost (UGX)')),
                ('branch', models.CharField(choices=[('Maganjo', 'Maganjo'), ('Matugga', 'Matugga')], max_length=20)),
                ('contact', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?\\d{9,15}$')])),
                ('selling_price_ugx', models.FloatField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('dealername', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.dealer')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.produce')),
            ],
        ),
        migrations.CreateModel(
            name='CreditSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Buyer Name')),
                ('national_id', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Enter a valid NIN', regex='^[A-Z0-9]{14}$')])),
                ('location', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('contact', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?\\d{9,15}$')])),
                ('amount_due_ugx', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(10000)])),
                ('due_date', models.DateField()),
                ('tonnage_kgs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_dispatch', models.DateField(auto_now_add=True)),
                ('branch', models.CharField(choices=[('Maganjo', 'Maganjo'), ('Matugga', 'Matugga')], max_length=20)),
                ('sales_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.produce', verbose_name='Produce Name')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonnage_kgs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid_ugx', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(10000)])),
                ('buyer_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('branch', models.CharField(choices=[('Maganjo', 'Maganjo'), ('Matugga', 'Matugga')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('produce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.produce')),
                ('sales_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('Maganjo', 'Maganjo'), ('Matugga', 'Matugga')], max_length=20)),
                ('tonnage_kgs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.produce')),
            ],
        ),
    ]
