# Generated by Django 5.2 on 2025-04-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='tonnage_kgs',
            new_name='price',
        ),
        migrations.AddField(
            model_name='dealer',
            name='dealer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('own_farm', 'Own Farm')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealer',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dealer',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
