# Generated by Django 5.2 on 2025-04-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_stock_price_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditsale',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
